services:
    app:
      container_name: activate-app
      platform: linux/x86_64
      build:
        context: .
        dockerfile: compose/app/Dockerfile
      restart: unless-stopped
      tty: true
      ports:
        - '${APP_PORT:-80}:80'
      env_file:
        - .env
      volumes:
        - app-volume:/var/www/html
      networks:
        - activate-net
      depends_on:
        - db
    db:
      container_name: activate-db
      platform: linux/x86_64
      image: mysql:latest
      restart: unless-stopped
      ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
      env_file:
        - .env
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_USER: '${DB_USERNAME}'
      volumes:
        - db-volume:/var/lib/mysql
      networks:
        - activate-net
      expose:
        - 3306

networks:
  activate-net:
    driver: bridge

volumes:
  db-volume:
    driver: local
  app-volume:
    driver: local

